# Generated by Django 5.1 on 2024-09-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_word_audio_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='session',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
