# Generated by Django 5.1 on 2024-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audio_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='mongo_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
